include(
    ":restdocs-api-spec",
    ":restdocs-api-spec-model",
    ":restdocs-api-spec-jsonschema",
    ":restdocs-api-spec-openapi3-generator",
    ":restdocs-api-spec-gradle-plugin",
    ":restdocs-api-spec-mockmvc",
    ":restdocs-api-spec-restassured",
    ":restdocs-api-spec-webtestclient",
)
